import type { PowerPlantType, FuelTankType, InstalledPowerPlant, InstalledFuelTank, PowerPlantStats } from '../types/powerPlant';
import type { Hull } from '../types/hull';
import { getPowerPlantsData, getFuelTankData } from './dataLoader';
import { generateId, validateMinSize, validateFuelTank } from './utilities';

/**
 * Get all power plant types
 */
export function getAllPowerPlantTypes(): PowerPlantType[] {
  return getPowerPlantsData();
}

/**
 * Get the fuel tank type definition
 */
export function getFuelTankType(): FuelTankType {
  return getFuelTankData();
}

/**
 * Get power plant types available for a specific ship class
 * Note: Currently all power plants are available for all ship classes
 */

export function getPowerPlantTypesForShipClass(): PowerPlantType[] {
  return getAllPowerPlantTypes();
}

/**
 * Get a power plant type by ID
 */
export function getPowerPlantTypeById(id: string): PowerPlantType | undefined {
  return getAllPowerPlantTypes().find((plant) => plant.id === id);
}

/**
 * Get power plant types that require fuel
 */
export function getFuelRequiringPlantTypes(): PowerPlantType[] {
  return getAllPowerPlantTypes().filter(plant => plant.requiresFuel);
}

/**
 * Calculate power generated by a power plant installation
 */
export function calculatePowerGenerated(plant: PowerPlantType, hullPoints: number): number {
  return plant.powerPerHullPoint * hullPoints;
}

/**
 * Calculate cost for a power plant installation
 */
export function calculatePowerPlantCost(plant: PowerPlantType, hullPoints: number): number {
  return plant.baseCost + (plant.costPerHullPoint * hullPoints);
}

/**
 * Calculate total cost for a fuel tank installation
 * Cost = tank base cost + tank cost per HP + fuel cost per HP (from power plant)
 */
export function calculateFuelTankCost(forPlantType: PowerPlantType, hullPoints: number): number {
  const fuelTankType = getFuelTankType();
  const tankCost = fuelTankType.baseCost + (fuelTankType.costPerHullPoint * hullPoints);
  const fuelCost = forPlantType.fuelCostPerHullPoint * hullPoints;
  return tankCost + fuelCost;
}

/**
 * Calculate endurance in days for a fuel tank
 * Fuel efficiency is power-days per hull point of fuel for a 1-hull-point plant
 */
export function calculateFuelTankEndurance(
  forPlantType: PowerPlantType,
  fuelTankHullPoints: number,
  plantHullPoints: number
): number {
  if (plantHullPoints === 0) return 0;
  const powerDaysPerFuelHP = forPlantType.fuelEfficiency / plantHullPoints;
  return Math.floor(powerDaysPerFuelHP * fuelTankHullPoints);
}

/**
 * Get total fuel tank HP for a specific power plant type
 */
export function getTotalFuelTankHPForPlantType(
  fuelTanks: InstalledFuelTank[],
  plantTypeId: string
): number {
  return fuelTanks
    .filter(tank => tank.forPowerPlantType.id === plantTypeId)
    .reduce((sum, tank) => sum + tank.hullPoints, 0);
}

/**
 * Get total fuel tank HP across all fuel tanks
 */
export function getTotalFuelTankHP(fuelTanks: InstalledFuelTank[]): number {
  return fuelTanks.reduce((sum, tank) => sum + tank.hullPoints, 0);
}

/**
 * Check if any installed power plant requires fuel
 */
export function hasFuelRequiringPlants(installations: InstalledPowerPlant[]): boolean {
  return installations.some(inst => inst.type.requiresFuel);
}

/**
 * Get installed power plants that require fuel
 */
export function getFuelRequiringInstallations(installations: InstalledPowerPlant[]): InstalledPowerPlant[] {
  return installations.filter(inst => inst.type.requiresFuel);
}

/**
 * Calculate total stats for an installed power plant
 */
export function calculatePowerPlantStats(installation: InstalledPowerPlant): PowerPlantStats {
  const { type, hullPoints } = installation;
  
  return {
    powerGenerated: calculatePowerGenerated(type, hullPoints),
    totalHullPoints: hullPoints,
    totalCost: calculatePowerPlantCost(type, hullPoints),
  };
}

/**
 * Calculate total stats for all installed power plants and fuel tanks
 */
export function calculateTotalPowerPlantStats(
  installations: InstalledPowerPlant[],
  fuelTanks: InstalledFuelTank[]
): {
  totalPowerGenerated: number;
  totalHullPoints: number;
  totalCost: number;
} {
  let totalPowerGenerated = 0;
  let totalHullPoints = 0;
  let totalCost = 0;
  
  // Add power plant stats
  for (const installation of installations) {
    const stats = calculatePowerPlantStats(installation);
    totalPowerGenerated += stats.powerGenerated;
    totalHullPoints += stats.totalHullPoints;
    totalCost += stats.totalCost;
  }
  
  // Add fuel tank stats
  for (const tank of fuelTanks) {
    totalHullPoints += tank.hullPoints;
    totalCost += calculateFuelTankCost(tank.forPowerPlantType, tank.hullPoints);
  }
  
  return {
    totalPowerGenerated,
    totalHullPoints,
    totalCost,
  };
}

/**
 * Validate a power plant installation
 */
export function validatePowerPlantInstallation(
  plant: PowerPlantType,
  hullPoints: number
): { valid: boolean; errors: string[] } {
  return validateMinSize(plant.name, hullPoints, plant.minSize);
}

/**
 * Validate a fuel tank installation
 */
export function validateFuelTankInstallation(
  hullPoints: number,
  hull: Hull,
  usedHullPoints: number
): { valid: boolean; errors: string[] } {
  return validateFuelTank(hullPoints, hull, usedHullPoints);
}

/**
 * Validate all power plant installations together (design-level validation)
 */
export function validatePowerPlantDesign(
  installations: InstalledPowerPlant[],
  fuelTanks: InstalledFuelTank[]
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check if fuel-requiring plants exist without fuel tanks
  const fuelRequiringPlants = getFuelRequiringInstallations(installations);
  
  for (const plant of fuelRequiringPlants) {
    const fuelTankHP = getTotalFuelTankHPForPlantType(fuelTanks, plant.type.id);
    if (fuelTankHP === 0) {
      errors.push(`Power plant "${plant.type.name}" requires fuel. Install at least one fuel tank for it.`);
    }
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Generate a unique installation ID for power plants
 */
export function generatePowerPlantId(): string {
  return generateId('pp');
}

/**
 * Generate a unique installation ID for fuel tanks
 */
export function generatePowerPlantFuelTankId(): string {
  return generateId('ft');
}
