import type { CharacterState } from '../types/characterState';

export function createEmptyCharacter(): CharacterState {
  return {
    level: 1,
    progressLevel: 6,
    selectedSourcePackIds: ['phb'],
    identity: {
      heroName: '',
      playerName: '',
      campaign: '',
      gamemaster: '',
      career: '',
      gender: '',
      age: '',
      height: '',
      weight: '',
      hair: '',
      eyes: '',
      appearance: '',
      background: '',
      allegiance: '',
      socialStatus: '',
      contacts: '',
      enemies: '',
      notes: '',
      motivation: '',
      moralAttitude: '',
      characterTraits: [],
    },
    speciesId: 'human',
    professionId: null,
    professionBenefits: {},
    speciesOptionIds: [],
    abilityScores: { str: 10, dex: 10, con: 10, int: 10, wil: 10, per: 10 },
    skillPlan: {
      nativeLanguage: '',
      cashedInFreeBroadSkillIds: [],
      purchasedBroadSkillIds: [],
      specialtySkills: [],
      additionalDiscountProfessionIds: [],
    },
    optionSelections: [],
    psionicPlan: {
      accessPath: 'none',
      purchasedBroadSkillIds: [],
      specialtySkills: [],
    },
    mutationPlan: {
      origin: 'natural',
      scope: 'individual',
      advantagePointBudget: 0,
      drawbackPointBudget: 0,
      selections: [],
    },
    cybergearSelections: [],
    startingFundsDieRolls: [],
    equipmentSelections: [],
    weaponSelections: [],
    armorSelections: [],
  };
}